/* main.c */
#include "main.h"

// Button definitions
#define BUTTON1_PIN        GPIO_PIN_0
#define BUTTON1_PORT       GPIOA
#define BUTTON2_PIN        GPIO_PIN_1
#define BUTTON2_PORT       GPIOA

// Motor control definitions
#define MOTOR_IN1_PIN      GPIO_PIN_0
#define MOTOR_IN1_PORT     GPIOB
#define MOTOR_IN2_PIN      GPIO_PIN_1
#define MOTOR_IN2_PORT     GPIOB
#define MOTOR_ENABLE_PIN   GPIO_PIN_2
#define MOTOR_ENABLE_PORT  GPIOB

#define DEBOUNCE_DELAY     20  // Задержка антидребезга в мс

// Global variables for debouncing
volatile uint32_t last_press_time = 0;
volatile uint8_t button_state = 0;  // 0 – none pressed, 1 – button1, 2 – button2

// Function prototypes
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
void Motor_Forward(void);
void Motor_Backward(void);
void Motor_Stop(void);


int main(void)
{
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    
    Motor_Stop();
    HAL_Delay(100);
    
    while (1)
    {
        uint32_t current_time = HAL_GetTick();
        
        // Testing button 1 (forward)
        if (HAL_GPIO_ReadPin(BUTTON1_PORT, BUTTON1_PIN) == GPIO_PIN_RESET)
        {
            // Debouncing
            if (current_time - last_press_time > DEBOUNCE_DELAY)
            {
                last_press_time = current_time;
                Motor_Forward();
            }
        }
        // Testing button 2 (backward)
        else if (HAL_GPIO_ReadPin(BUTTON2_PORT, BUTTON2_PIN) == GPIO_PIN_RESET)
        {
            if (current_time - last_press_time > DEBOUNCE_DELAY)
            {
                last_press_time = current_time;
                Motor_Backward();
            }
        }
        // If no button is pressed, stop the motor
        else
        {
            Motor_Stop();
        }
        
        HAL_Delay(10);
    }
}

void Motor_Forward(void)
{
    HAL_GPIO_WritePin(MOTOR_IN1_PORT, MOTOR_IN1_PIN, GPIO_PIN_SET);
    HAL_GPIO_WritePin(MOTOR_IN2_PORT, MOTOR_IN2_PIN, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(MOTOR_ENABLE_PORT, MOTOR_ENABLE_PIN, GPIO_PIN_SET);
}

void Motor_Backward(void)
{
    HAL_GPIO_WritePin(MOTOR_IN1_PORT, MOTOR_IN1_PIN, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(MOTOR_IN2_PORT, MOTOR_IN2_PIN, GPIO_PIN_SET);
    HAL_GPIO_WritePin(MOTOR_ENABLE_PORT, MOTOR_ENABLE_PIN, GPIO_PIN_SET);
}

void Motor_Stop(void)
{
    HAL_GPIO_WritePin(MOTOR_ENABLE_PORT, MOTOR_ENABLE_PIN, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(MOTOR_IN1_PORT, MOTOR_IN1_PIN, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(MOTOR_IN2_PORT, MOTOR_IN2_PIN, GPIO_PIN_RESET);
}

static void MX_GPIO_Init(void)
{
    GPIO_InitTypeDef GPIO_InitStruct = {0};
    
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();
    
    // Initial state of outputs
    HAL_GPIO_WritePin(GPIOB, MOTOR_IN1_PIN|MOTOR_IN2_PIN|MOTOR_ENABLE_PIN, GPIO_PIN_RESET);
    
    // Buttons – inputs with pull-up resistors
    GPIO_InitStruct.Pin = BUTTON1_PIN|BUTTON2_PIN;
    GPIO_InitStruct.Mode = GPIO_MODE_INPUT;
    GPIO_InitStruct.Pull = GPIO_PULLUP;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
    
    // Motor outputs
    GPIO_InitStruct.Pin = MOTOR_IN1_PIN|MOTOR_IN2_PIN|MOTOR_ENABLE_PIN;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);
}

void SystemClock_Config(void)
{
    // Clock configuration (generated by CubeMX)
    RCC_OscInitTypeDef RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};
    
    RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
    RCC_OscInitStruct.HSEState = RCC_HSE_ON;
    RCC_OscInitStruct.HSEPredivValue = RCC_HSE_PREDIV_DIV1;
    RCC_OscInitStruct.HSIState = RCC_HSI_ON;
    RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
    RCC_OscInitStruct.PLL.PLLMUL = RCC_PLL_MUL9;
    
    if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
    {
        Error_Handler();
    }
    
    RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                                |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;
    
    if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK)
    {
        Error_Handler();
    }
}

void Error_Handler(void)
{
    __disable_irq();
    while (1)
    {
    }
}
